name: ml-catalogue
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - joblib=1.5.2=py311hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.30=hf2bb037_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - ncurses=6.5=hee39554_0
  - numexpr=2.11.0=py311h8c72970_1
  - numpy=2.3.3=py311hc95ac1c_1
  - numpy-base=2.3.3=py311h8087a70_1
  - openssl=3.0.18=h9b4081a_0
  - pandas=2.3.3=py311hc6ded6b_0
  - pip=25.2=pyhc872135_1
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311hca03da5_0
  - readline=8.3=h0b18652_0
  - scikit-learn=1.7.2=py311hc6ded6b_0
  - scipy=1.16.2=py311h53ebd84_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
prefix: /Users/martinbergsto/anaconda3/envs/ml-catalogue
